<?php


/**
 * Skeleton subclass for representing a row from the 'cre8_session_storage' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.1 on:
 *
 * pon, 24 maj 2010, 12:58:08
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.cre8SessionStoragePlugin.lib.model
 */
class cre8SessionStorage extends Basecre8SessionStorage {

} // cre8SessionStorage
