<?php



/**
 * Skeleton subclass for performing query and update operations on the 'cre8_login_history' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.2-dev on:
 *
 * pią, 4 cze 2010, 09:51:40
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.cre8SessionStoragePlugin.lib.model
 */
class cre8LoginHistoryPeer extends Basecre8LoginHistoryPeer {

} // cre8LoginHistoryPeer
